"""add ai_words_research_logs table

Revision ID: 0e97494ca404
Revises: b9d0e1f2g3h4
Create Date: 2026-05-13 11:11:41.881742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e97494ca404'
down_revision = 'b9d0e1f2g3h4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only create ai_words_research_logs table - other tables already exist
    op.create_table('ai_words_research_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('found_total', sa.Integer(), nullable=False),
    sa.Column('new_count', sa.Integer(), nullable=False),
    sa.Column('new_words', sa.JSON(), nullable=True),
    sa.Column('sources_checked', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_words_research_logs')
    # ### end Alembic commands ###
