"""add ai_words_research_logs table

Revision ID: 0e97494ca404
Revises: b9d0e1f2g3h4
Create Date: 2026-05-13 11:11:41.881742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e97494ca404'
down_revision = 'b9d0e1f2g3h4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_words_research_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('found_total', sa.Integer(), nullable=False),
    sa.Column('new_count', sa.Integer(), nullable=False),
    sa.Column('new_words', sa.JSON(), nullable=True),
    sa.Column('sources_checked', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('config', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('crawl_interval_min', sa.Integer(), nullable=False),
    sa.Column('last_crawled_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_sources_user_id'), 'job_sources', ['user_id'], unique=False)
    op.create_table('cover_letters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('cv_used', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('analysis_json', sa.Text(), nullable=True),
    sa.Column('tone', sa.String(length=50), nullable=True),
    sa.Column('length', sa.String(length=50), nullable=True),
    sa.Column('focus', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('exported_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cover_letters_user_id'), 'cover_letters', ['user_id'], unique=False)
    op.create_table('raw_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=512), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('crawl_status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['job_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_raw_job_source_external')
    )
    op.create_index(op.f('ix_raw_jobs_source_id'), 'raw_jobs', ['source_id'], unique=False)
    op.create_index('ix_raw_jobs_status', 'raw_jobs', ['crawl_status'], unique=False)
    op.create_table('job_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_job_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('prefilter_score', sa.Float(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('match_reasoning', sa.Text(), nullable=True),
    sa.Column('missing_skills', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.Column('imported_application_id', sa.String(length=36), nullable=True),
    sa.Column('suspicious_reasons', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['imported_application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['raw_job_id'], ['raw_jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_job_id', 'user_id', name='uq_match_job_user')
    )
    op.create_index('ix_match_prefilter_pending', 'job_matches', ['prefilter_score'], unique=False)
    op.create_index('ix_match_user_status_score', 'job_matches', ['user_id', 'status', 'match_score'], unique=False)
    op.add_column('api_calls', sa.Column('key_owner', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('job_discovery_enabled', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('job_discovery_requested_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('job_notification_threshold', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('job_claude_budget_per_tick', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('job_daily_budget_cents', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('job_language_filter', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('job_region_filter', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('job_reject_filter_enabled', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('job_reject_window_days', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('feature_model_overrides', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('ai_provider_backup', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('ai_provider_backup_model', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ai_provider_backup_model')
    op.drop_column('users', 'ai_provider_backup')
    op.drop_column('users', 'feature_model_overrides')
    op.drop_column('users', 'job_reject_window_days')
    op.drop_column('users', 'job_reject_filter_enabled')
    op.drop_column('users', 'job_region_filter')
    op.drop_column('users', 'job_language_filter')
    op.drop_column('users', 'job_daily_budget_cents')
    op.drop_column('users', 'job_claude_budget_per_tick')
    op.drop_column('users', 'job_notification_threshold')
    op.drop_column('users', 'job_discovery_requested_at')
    op.drop_column('users', 'job_discovery_enabled')
    op.drop_column('api_calls', 'key_owner')
    op.drop_index('ix_match_user_status_score', table_name='job_matches')
    op.drop_index('ix_match_prefilter_pending', table_name='job_matches')
    op.drop_table('job_matches')
    op.drop_index('ix_raw_jobs_status', table_name='raw_jobs')
    op.drop_index(op.f('ix_raw_jobs_source_id'), table_name='raw_jobs')
    op.drop_table('raw_jobs')
    op.drop_index(op.f('ix_cover_letters_user_id'), table_name='cover_letters')
    op.drop_table('cover_letters')
    op.drop_index(op.f('ix_job_sources_user_id'), table_name='job_sources')
    op.drop_table('job_sources')
    op.drop_table('ai_words_research_logs')
    # ### end Alembic commands ###
