"""Add backup history table

Revision ID: 6282fb5759aa
Revises: 001
Create Date: 2026-04-24 03:34:10.231337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6282fb5759aa'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('encrypted_data', sa.Text(), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('backup_type', sa.String(length=20), nullable=True),
    sa.Column('summary', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backup_history_created_at'), 'backup_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_backup_history_user_id'), 'backup_history', ['user_id'], unique=False)
    op.create_table('email_confirmation_tokens',
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_email_confirmation_tokens_user_id'), 'email_confirmation_tokens', ['user_id'], unique=False)
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('email_confirmed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'email_confirmed')
    op.drop_column('users', 'is_admin')
    op.drop_index(op.f('ix_email_confirmation_tokens_user_id'), table_name='email_confirmation_tokens')
    op.drop_table('email_confirmation_tokens')
    op.drop_index(op.f('ix_backup_history_user_id'), table_name='backup_history')
    op.drop_index(op.f('ix_backup_history_created_at'), table_name='backup_history')
    op.drop_table('backup_history')
    # ### end Alembic commands ###
